export const PATH = {
    ACCOUNT_MANAGEMENT: 'account-management',
    CREATE_NEW_PASSWORD: '/auth/create-new-password',
    DEVICES: 'devices',
    EXPIRED_LINK: '/auth/email-resending',
    FAVORITES: '/profile/favorites',
    FORGOT_PASSWORD: '/auth/forgot-password',
    GENERAL_INFORMATION: 'general-information',
    HOME: '/profile',
    LOG_OUT: '/auth/logout',
    LOGIN: '/auth/login',
    MESSENGER: '/profile/messenger',
    MY_PAYMENTS: 'my-payments',
    MY_PROFILE: '/profile/my-profile',
    PRIVACY_POLICY: '/auth/privacy-policy',
    PROFILE_SETTINGS: `/profile/settings/general-information`,
    PUBLIC: {
        PROFILE: 'public/profile',
    },
    REGISTRATION: '/auth/registration',
    REGISTRATION_CONFIRMED: '/auth/registrationConfirmed',
    SEARCH: '/profile/search',
    SETTINGS: 'settings',
    STATISTICS: '/profile/statistics',
    TERMS_OF_SERVICE: '/auth/terms-of-service',
    UPDATE_TOKENS: '/auth/update-tokens',
    USER_PROFILE: '/profile/user-profile',
    VIEW_POST: '/profile/view-post',
} as const
